services:
  aero-seeker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aero-seeker
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - aero-seeker-network

networks:
  aero-seeker-network:
    driver: bridge
